# Generated by Django 3.1.3 on 2021-01-10 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('aid', models.AutoField(max_length=3, primary_key=True, serialize=False)),
                ('atype1', models.CharField(blank=True, max_length=10, null=True)),
                ('atype2', models.CharField(blank=True, max_length=10, null=True)),
                ('tasknum', models.IntegerField(blank=True, null=True)),
                ('tasksum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Enroll',
                'ordering': ['tid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tname', models.CharField(blank=True, max_length=20, null=True, verbose_name='任务名')),
                ('intro', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务简介')),
                ('tstart', models.TimeField(default=datetime.datetime(2021, 1, 10, 8, 32, 16, 938844, tzinfo=utc), verbose_name='开始时间')),
                ('tend', models.TimeField(default=datetime.datetime(2021, 1, 10, 8, 32, 16, 938870, tzinfo=utc), verbose_name='结束时间')),
            ],
            options={
                'db_table': 'Task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
